# Generated by Django 5.2.8 on 2026-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_projectmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('agents', 'Agents'), ('rag', 'RAG'), ('chatbot', 'Chatbot'), ('backend', 'Backend'), ('fullstack', 'FullStack')], default='backend', max_length=20),
        ),
    ]
