# Generated by Django 6.0.5 on 2026-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='pin_order',
            field=models.IntegerField(default=0),
        ),
    ]
